# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: lin-ycv.EverythingPowerToys
PackageVersion: 0.91.1
Platform:
- Windows.Desktop
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.PowerToys
InstallationMetadata:
  DefaultInstallLocation: '%LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Plugins\Everything'
  Files:
  - RelativeFilePath: plugin.json
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/lin-ycv/EverythingPowerToys/releases/download/v0.91.1/EverythingPT-0.91.1-x64.zip
  InstallerSha256: 1ab45af0a4e8c39dd355a7264629911ab14ab12f3231a49849a69c0570de8790
- Architecture: arm64
  InstallerUrl: https://github.com/lin-ycv/EverythingPowerToys/releases/download/v0.91.1/EverythingPT-0.91.1-ARM64.zip
  InstallerSha256: 67762f69d55af8efb13c36e21a3bf484d2efa49285a28e05975d64cddc508c98
ManifestType: installer
ManifestVersion: 1.9.0
