PackageIdentifier: lin-ycv.EverythingPowerToys
PackageVersion: 0.91.1
Platform:
  - Windows.Desktop
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
InstallationMetadata:
  DefaultInstallLocation: '%LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Plugins\Everything'
  Files:
    - RelativeFilePath: plugin.json
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.PowerToys
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/lin-ycv/EverythingPowerToys/releases/download/v0.91.1/EverythingPT-0.91.1-x64.exe
    InstallerSha256: fde6db1393bc8e6ba0e09236ce238c752dcc93571dadf6c02a6b6e10f6004478
  - Architecture: arm64
    InstallerUrl: https://github.com/lin-ycv/EverythingPowerToys/releases/download/v0.91.1/EverythingPT-0.91.1-ARM64.exe
    InstallerSha256: ccaad6df6f5bbfa3ce3192f7f80fe3cd3d3b4a05ac1423fa9455a1b8fdc12fe3
ManifestType: installer
ManifestVersion: 1.9.0
